on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - main
      - master
name: Run tests
jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu", "windows", "macos"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        run: go test ./...
      - name: Test 32 bit
        if: ${{ matrix.os != 'macos' }} # can't run 32 bit tests on OSX.
        env:
          GOARCH: 386
        run: go test ./...
      - name: Test with race detector
        if: ${{ matrix.os == 'ubuntu' }} # speed things up. Windows and OSX VMs are slow
        run: go test -race ./...
